#!/usr/bin/env python3
"""Generate src/data/bgdata.s from the Python port's BGDATA tables."""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(HERE.parent / "PrinceOfPersiaPy" / "src"))
from graphics import bgdata as BG  # noqa: E402

TABLES = [
    "PIECEA", "PIECEAY", "PIECEB", "PIECEBY", "BSTRIPE", "PIECEC", "PIECED",
    "FRONTI", "FRONTY", "FRONTX",
    "GATE8B", "GATE8C", "SPIKEA", "SPIKEB",
    "LOOSEA", "LOOSEBY", "LOOSED",
    "SLICERSEQ", "SLICERTOP", "SLICERBOT", "SLICERFRNT",
    "BLOCKB", "BLOCKC", "BLOCKD", "BLOCKFR",
    "PANELB", "PANELC", "SPACEB", "SPACEBY", "FLOORB", "TORCHFLAME",
]
CONSTS = ["GATEBOT_STA", "GATEBOT_ORA", "GATE_B1", "EXIT_STAIRS", "EXIT_DOOR",
          "EXIT_TOP", "LOOSE_B", "SPECIALFLASK", "SWORDGLEAM0", "SWORDGLEAM1",
          "SPIKE_EXT", "SPIKE_RET", "SLICER_EXT"]


def main():
    lines = ["; Generated by tools/gen_bgdata.py from BGDATA tables. Do not edit.",
             "", '        .segment "RODATA"']
    for name in CONSTS:
        lines.append(f"BG_{name} = ${getattr(BG, name):02x}")
        lines.append(f"        .export BG_{name}")
    lines.append("")
    for name in TABLES:
        vals = getattr(BG, name)
        lines.append(f"        .export BG_{name}")
        lines.append(f"BG_{name}:")
        lines.append("        .byte " + ",".join(
            f"${v & 0xff:02x}" for v in vals))
    # gate bar lift in px for position>>2 (pos*44/188, pos 0..188)
    lines.append("        .export BG_GATELIFT")
    lines.append("BG_GATELIFT:")
    lines.append("        .byte " + ",".join(
        f"${min(i * 4, 188) * 44 // 188:02x}" for i in range(48)))
    out = HERE / "src" / "data" / "bgdata.s"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(HERE)} "
          f"({sum(len(getattr(BG, t)) for t in TABLES)} table bytes)")


if __name__ == "__main__":
    main()
