#!/usr/bin/env python3
"""Generate ca65 source for the original animation data tables.

Reads the machine-translated tables from ../PrinceOfPersiaPy/src/data/
(SEQTABLE bytecode, FRAMEDEF frame definitions) and emits:

    src/data/seqtable.s  — original sequence bytecode, verbatim
    src/data/framedef.s  — frame defs as parallel byte tables (struct of
                           arrays, for indexed 6502 addressing)

The SEQTABLE contains absolute 2-byte GOTO addresses assembled at ORG $3000;
the C64 interpreter rebases them with a page delta, so the bytes stay
verbatim. Frame dx/dy are signed, stored as two's complement.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
PY_REPO = HERE.parent / "PrinceOfPersiaPy"
OUT_DIR = HERE / "src" / "data"

sys.path.insert(0, str(PY_REPO / "src"))
from data import framedefs, seqdata  # noqa: E402


def byte_rows(data, per_row=16):
    for i in range(0, len(data), per_row):
        chunk = data[i:i + per_row]
        yield "        .byte " + ",".join(f"${b & 0xff:02x}" for b in chunk)


def emit_seqtable():
    lines = [
        "; Generated by tools/gen_anim_data.py from SEQTABLE.S data. Do not edit.",
        "; Original ORG $3000; GOTO operands are absolute addresses in that space.",
        "",
        f"        .export SEQTABLE",
        f"        .export SEQ_ORG_HI",
        f"SEQ_ORG_HI = ${seqdata.ORG >> 8:02x}",
        "",
    ]
    # sequence label offsets (and end-of-sequence offsets for range checks)
    starts = sorted(seqdata.LABELS.values())
    for name, off in sorted(seqdata.LABELS.items()):
        i = starts.index(off)
        end = starts[i + 1] if i + 1 < len(starts) else len(seqdata.SEQ_BYTES)
        lines.append(f"SEQ_{name} = {off}")
        lines.append(f"SEQEND_{name} = {end}")
        lines.append(f"        .export SEQ_{name} : absolute, "
                     f"SEQEND_{name} : absolute")
    lines += [
        "",
        '        .segment "ANIMDATA"',
        "SEQTABLE:",
    ]
    lines += byte_rows(seqdata.SEQ_BYTES)
    lines.append(f"; {len(seqdata.SEQ_BYTES)} bytes")
    lines.append("")
    return "\n".join(lines)


def parallel_tables(name, table, fields):
    """Emit a dict {index: tuple} as per-field byte tables, dense from min key."""
    lo, hi = min(table), max(table)
    out = [f"{name}_BASE = {lo}", f"{name}_COUNT = {hi - lo + 1}"]
    for fi, field in enumerate(fields):
        out.append(f"        .export {name}_{field}")
        out.append(f"{name}_{field}:")
        data = [table.get(k, (0,) * len(fields))[fi] for k in range(lo, hi + 1)]
        out += byte_rows(data)
    return out


def emit_framedef():
    lines = [
        "; Generated by tools/gen_anim_data.py from FRAMEDEF.S data. Do not edit.",
        "; MAIN/ALTSET1/ALTSET2: (image, sword, dx, dy, check) per frame id.",
        "; SWORDTAB: sword overlay frames.",
        "",
        '        .segment "ANIMDATA"',
    ]
    fields = ("IMAGE", "SWORD", "DX", "DY", "CHK")
    lines += parallel_tables("FD_MAIN", framedefs.MAIN, fields)
    lines += parallel_tables("FD_ALT1", framedefs.ALTSET1, fields)
    swfields = ("F0", "F1", "F2")
    lines += parallel_tables("SWORDTAB", framedefs.SWORDTAB, swfields)
    # ALTSET2 (princess/vizier) returns with the endgame build
    lines.append("")
    return "\n".join(lines)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "seqtable.s").write_text(emit_seqtable())
    (OUT_DIR / "framedef.s").write_text(emit_framedef())
    total = sum(len((OUT_DIR / f).read_text()) for f in ("seqtable.s", "framedef.s"))
    print(f"wrote src/data/seqtable.s ({len(seqdata.SEQ_BYTES)} table bytes)")
    print(f"wrote src/data/framedef.s "
          f"(MAIN {len(framedefs.MAIN)}, ALT1 {len(framedefs.ALTSET1)}, "
          f"ALT2 {len(framedefs.ALTSET2)}, SWORD {len(framedefs.SWORDTAB)} entries)")


if __name__ == "__main__":
    main()
