; Generated by tools/gen_bgdata.py from BGDATA tables. Do not edit.

        .segment "RODATA"
BG_GATEBOT_STA = $43
        .export BG_GATEBOT_STA
BG_GATEBOT_ORA = $44
        .export BG_GATEBOT_ORA
BG_GATE_B1 = $37
        .export BG_GATE_B1
BG_EXIT_STAIRS = $6b
        .export BG_EXIT_STAIRS
BG_EXIT_DOOR = $6c
        .export BG_EXIT_DOOR
BG_EXIT_TOP = $6e
        .export BG_EXIT_TOP
BG_LOOSE_B = $1b
        .export BG_LOOSE_B
BG_SPECIALFLASK = $95
        .export BG_SPECIALFLASK
BG_SWORDGLEAM0 = $99
        .export BG_SWORDGLEAM0
BG_SWORDGLEAM1 = $b3
        .export BG_SWORDGLEAM1
BG_SPIKE_EXT = $05
        .export BG_SPIKE_EXT
BG_SPIKE_RET = $09
        .export BG_SPIKE_RET
BG_SLICER_EXT = $02
        .export BG_SLICER_EXT

        .export BG_PIECEA
BG_PIECEA:
        .byte $00,$01,$05,$07,$0a,$01,$01,$0a,$10,$00,$01,$00,$00,$14,$20,$4b,$01,$00,$00,$01,$00,$97,$00,$01,$00,$a7,$a9,$aa,$ac,$ad
        .export BG_PIECEAY
BG_PIECEAY:
        .byte $00,$00,$00,$00,$00,$01,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$fc,$fc,$fc
        .export BG_PIECEB
BG_PIECEB:
        .byte $00,$02,$06,$08,$0b,$1b,$02,$9e,$1a,$1c,$02,$00,$9e,$4a,$21,$1b,$4d,$4e,$02,$51,$84,$98,$02,$91,$92,$02,$00,$00,$00,$00
        .export BG_PIECEBY
BG_PIECEBY:
        .byte $00,$00,$00,$00,$00,$01,$00,$03,$00,$03,$00,$00,$03,$00,$00,$ff,$00,$00,$00,$ff,$02,$00,$00,$00,$00,$00,$00,$00,$00,$00
        .export BG_BSTRIPE
BG_BSTRIPE:
        .byte $00,$47,$47,$00,$00,$47,$47,$00,$00,$00,$47,$47,$00,$00,$47,$47,$00,$00,$47,$00,$00,$00,$47,$00,$00,$47,$00,$00,$00,$00
        .export BG_PIECEC
BG_PIECEC:
        .byte $00,$00,$00,$09,$0c,$00,$00,$9f,$00,$1d,$00,$00,$9f,$00,$00,$00,$4f,$50,$00,$00,$85,$00,$00,$93,$94,$00,$00,$00,$00,$00
        .export BG_PIECED
BG_PIECED:
        .byte $00,$15,$15,$15,$15,$18,$19,$16,$15,$00,$15,$00,$17,$15,$2e,$4c,$15,$15,$15,$15,$86,$15,$15,$15,$15,$15,$ab,$00,$00,$00
        .export BG_FRONTI
BG_FRONTI:
        .byte $00,$00,$00,$45,$46,$00,$00,$46,$48,$49,$87,$00,$46,$0f,$13,$00,$00,$00,$00,$00,$83,$00,$00,$00,$00,$a8,$00,$ae,$ae,$ae
        .export BG_FRONTY
BG_FRONTY:
        .byte $00,$00,$00,$ff,$00,$00,$00,$00,$ff,$03,$fd,$00,$00,$ff,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$ff,$00,$dc,$dc,$dc
        .export BG_FRONTX
BG_FRONTX:
        .byte $00,$00,$00,$01,$03,$00,$00,$03,$01,$01,$02,$00,$03,$01,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$01,$00,$00,$00,$00
        .export BG_GATE8B
BG_GATE8B:
        .byte $3e,$3d,$3c,$3b,$3a,$39,$38,$37
        .export BG_GATE8C
BG_GATE8C:
        .byte $2f,$30,$31,$32,$33,$34,$35,$36
        .export BG_SPIKEA
BG_SPIKEA:
        .byte $00,$22,$24,$26,$28,$2a,$28,$24,$22,$00
        .export BG_SPIKEB
BG_SPIKEB:
        .byte $00,$23,$25,$27,$29,$2b,$29,$25,$23,$00
        .export BG_LOOSEA
BG_LOOSEA:
        .byte $01,$1e,$01,$1f,$1f,$01,$01,$01,$1f,$1f,$1f
        .export BG_LOOSEBY
BG_LOOSEBY:
        .byte $00,$01,$00,$ff,$ff,$00,$00,$00,$ff,$ff,$ff
        .export BG_LOOSED
BG_LOOSED:
        .byte $15,$2c,$15,$2d,$2d,$15,$15,$15,$2d,$2d,$2d
        .export BG_SLICERSEQ
BG_SLICERSEQ:
        .byte $04,$03,$01,$02,$05,$04,$04
        .export BG_SLICERTOP
BG_SLICERTOP:
        .byte $00,$58,$5a,$5c,$5e
        .export BG_SLICERBOT
BG_SLICERBOT:
        .byte $57,$59,$5b,$5d,$5f
        .export BG_SLICERFRNT
BG_SLICERFRNT:
        .byte $65,$66,$67,$68,$69
        .export BG_BLOCKB
BG_BLOCKB:
        .byte $84,$6f
        .export BG_BLOCKC
BG_BLOCKC:
        .byte $85,$85
        .export BG_BLOCKD
BG_BLOCKD:
        .byte $86,$86
        .export BG_BLOCKFR
BG_BLOCKFR:
        .byte $83,$83
        .export BG_PANELB
BG_PANELB:
        .byte $9e,$9a,$81
        .export BG_PANELC
BG_PANELC:
        .byte $9f,$9b,$82
        .export BG_SPACEB
BG_SPACEB:
        .byte $00,$a3,$a5,$a6
        .export BG_SPACEBY
BG_SPACEBY:
        .byte $00,$ec,$ec,$00
        .export BG_FLOORB
BG_FLOORB:
        .byte $02,$a2,$a4,$a4
        .export BG_TORCHFLAME
BG_TORCHFLAME:
        .byte $52,$53,$54,$55,$56,$61,$62,$63,$64,$52,$54,$56
        .export BG_GATELIFT
BG_GATELIFT:
        .byte $00,$00,$01,$02,$03,$04,$05,$06,$07,$08,$09,$0a,$0b,$0c,$0d,$0e,$0e,$0f,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$1a,$1b,$1c,$1d,$1d,$1e,$1f,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$2a,$2b,$2c
