; Generated by tools/gen_anim_data.py from SEQTABLE.S data. Do not edit.
; Original ORG $3000; GOTO operands are absolute addresses in that space.

        .export SEQTABLE
        .export SEQ_ORG_HI
SEQ_ORG_HI = $30

SEQ_Mclimb = 2541
SEQEND_Mclimb = 2546
        .export SEQ_Mclimb : absolute, SEQEND_Mclimb : absolute
SEQ_Mleave = 2522
SEQEND_Mleave = 2541
        .export SEQ_Mleave : absolute, SEQEND_Mleave : absolute
SEQ_Mraise = 2518
SEQEND_Mraise = 2522
        .export SEQ_Mraise : absolute, SEQEND_Mraise : absolute
SEQ_Mscurry = 2500
SEQEND_Mscurry = 2502
        .export SEQ_Mscurry : absolute, SEQEND_Mscurry : absolute
SEQ_Mscurry1 = 2502
SEQEND_Mscurry1 = 2514
        .export SEQ_Mscurry1 : absolute, SEQEND_Mscurry1 : absolute
SEQ_Mstop = 2514
SEQEND_Mstop = 2518
        .export SEQ_Mstop : absolute, SEQEND_Mstop : absolute
SEQ_Palert = 2328
SEQEND_Palert = 2343
        .export SEQ_Palert : absolute, SEQEND_Palert : absolute
SEQ_Pback = 2343
SEQEND_Pback = 2363
        .export SEQ_Pback : absolute, SEQEND_Pback : absolute
SEQ_Pcrouch = 2427
SEQEND_Pcrouch = 2495
        .export SEQ_Pcrouch : absolute, SEQEND_Pcrouch : absolute
SEQ_Pembrace = 2371
SEQEND_Pembrace = 2405
        .export SEQ_Pembrace : absolute, SEQEND_Pembrace : absolute
SEQ_Plie = 2363
SEQEND_Plie = 2367
        .export SEQ_Plie : absolute, SEQEND_Plie : absolute
SEQ_Prise = 2409
SEQEND_Prise = 2427
        .export SEQ_Prise : absolute, SEQEND_Prise : absolute
SEQ_Pslump = 2495
SEQEND_Pslump = 2500
        .export SEQ_Pslump : absolute, SEQEND_Pslump : absolute
SEQ_Pstand = 2324
SEQEND_Pstand = 2328
        .export SEQ_Pstand : absolute, SEQEND_Pstand : absolute
SEQ_Pstroke = 2405
SEQEND_Pstroke = 2409
        .export SEQ_Pstroke : absolute, SEQEND_Pstroke : absolute
SEQ_Pwaiting = 2367
SEQEND_Pwaiting = 2371
        .export SEQ_Pwaiting : absolute, SEQEND_Pwaiting : absolute
SEQ_Vexit = 2284
SEQEND_Vexit = 2324
        .export SEQ_Vexit : absolute, SEQEND_Vexit : absolute
SEQ_Vraise = 2233
SEQEND_Vraise = 2254
        .export SEQ_Vraise : absolute, SEQEND_Vraise : absolute
SEQ_Vstand = 2229
SEQEND_Vstand = 2233
        .export SEQ_Vstand : absolute, SEQEND_Vstand : absolute
SEQ_Vstop = 2277
SEQEND_Vstop = 2284
        .export SEQ_Vstop : absolute, SEQEND_Vstop : absolute
SEQ_Vwalk = 2254
SEQEND_Vwalk = 2256
        .export SEQ_Vwalk : absolute, SEQEND_Vwalk : absolute
SEQ_Vwalk1 = 2256
SEQEND_Vwalk1 = 2259
        .export SEQ_Vwalk1 : absolute, SEQEND_Vwalk1 : absolute
SEQ_Vwalk2 = 2259
SEQEND_Vwalk2 = 2277
        .export SEQ_Vwalk2 : absolute, SEQEND_Vwalk2 : absolute
SEQ_advance = 393
SEQEND_advance = 408
        .export SEQ_advance : absolute, SEQEND_advance : absolute
SEQ_alertstand = 286
SEQEND_alertstand = 290
        .export SEQ_alertstand : absolute, SEQEND_alertstand : absolute
SEQ_alertturn = 513
SEQEND_alertturn = 521
        .export SEQ_alertturn : absolute, SEQEND_alertturn : absolute
SEQ_arise = 290
SEQEND_arise = 311
        .export SEQ_arise : absolute, SEQEND_arise : absolute
SEQ_blockedstrike = 458
SEQEND_blockedstrike = 464
        .export SEQ_blockedstrike : absolute, SEQEND_blockedstrike : absolute
SEQ_blocking = 469
SEQEND_blocking = 473
        .export SEQ_blocking : absolute, SEQEND_blocking : absolute
SEQ_blocktostrike = 464
SEQEND_blocktostrike = 468
        .export SEQ_blocktostrike : absolute, SEQEND_blocktostrike : absolute
SEQ_bump = 1397
SEQEND_bump = 1407
        .export SEQ_bump : absolute, SEQEND_bump : absolute
SEQ_bumpengback = 491
SEQEND_bumpengback = 498
        .export SEQ_bumpengback : absolute, SEQEND_bumpengback : absolute
SEQ_bumpengfwd = 484
SEQEND_bumpengfwd = 491
        .export SEQ_bumpengfwd : absolute, SEQEND_bumpengfwd : absolute
SEQ_bumpfall = 1407
SEQEND_bumpfall = 1438
        .export SEQ_bumpfall : absolute, SEQEND_bumpfall : absolute
SEQ_bumpfloat = 1438
SEQEND_bumpfloat = 1460
        .export SEQ_bumpfloat : absolute, SEQEND_bumpfloat : absolute
SEQ_climbdown = 1123
SEQEND_climbdown = 1145
        .export SEQ_climbdown : absolute, SEQEND_climbdown : absolute
SEQ_climbfail = 1107
SEQEND_climbfail = 1123
        .export SEQ_climbfail : absolute, SEQEND_climbfail : absolute
SEQ_climbstairs = 2136
SEQEND_climbstairs = 2229
        .export SEQ_climbstairs : absolute, SEQEND_climbstairs : absolute
SEQ_climbup = 1145
SEQEND_climbup = 1178
        .export SEQ_climbup : absolute, SEQEND_climbup : absolute
SEQ_crawl = 656
SEQEND_crawl = 656
        .export SEQ_crawl : absolute, SEQEND_crawl : absolute
SEQ_crush = 2124
SEQEND_crush = 2127
        .export SEQ_crush : absolute, SEQEND_crush : absolute
SEQ_deadfall = 2127
SEQEND_deadfall = 2136
        .export SEQ_deadfall : absolute, SEQEND_deadfall : absolute
SEQ_drinkpotion = 1922
SEQEND_drinkpotion = 1954
        .export SEQ_drinkpotion : absolute, SEQEND_drinkpotion : absolute
SEQ_dropdead = 2089
SEQEND_dropdead = 2105
        .export SEQ_dropdead : absolute, SEQEND_dropdead : absolute
SEQ_efightfall = 790
SEQEND_efightfall = 820
        .export SEQ_efightfall : absolute, SEQEND_efightfall : absolute
SEQ_efightfallfwd = 820
SEQEND_efightfallfwd = 848
        .export SEQ_efightfallfwd : absolute, SEQEND_efightfallfwd : absolute
SEQ_engarde = 314
SEQEND_engarde = 328
        .export SEQ_engarde : absolute, SEQEND_engarde : absolute
SEQ_fall1 = 857
SEQEND_fall1 = 879
        .export SEQ_fall1 : absolute, SEQEND_fall1 : absolute
SEQ_fallhang = 1389
SEQEND_fallhang = 1397
        .export SEQ_fallhang : absolute, SEQEND_fallhang : absolute
SEQ_fastadvance = 408
SEQEND_fastadvance = 420
        .export SEQ_fastadvance : absolute, SEQEND_fastadvance : absolute
SEQ_fastsheathe = 1908
SEQEND_fastsheathe = 1922
        .export SEQ_fastsheathe : absolute, SEQEND_fastsheathe : absolute
SEQ_faststrike = 440
SEQEND_faststrike = 442
        .export SEQ_faststrike : absolute, SEQEND_faststrike : absolute
SEQ_fightfall = 762
SEQEND_fightfall = 790
        .export SEQ_fightfall : absolute, SEQEND_fightfall : absolute
SEQ_finishturn = 700
SEQEND_finishturn = 712
        .export SEQ_finishturn : absolute, SEQEND_finishturn : absolute
SEQ_flee = 498
SEQEND_flee = 505
        .export SEQ_flee : absolute, SEQEND_flee : absolute
SEQ_freefall = 1216
SEQEND_freefall = 1222
        .export SEQ_freefall : absolute, SEQEND_freefall : absolute
SEQ_fullstep = 1526
SEQEND_fullstep = 1526
        .export SEQ_fullstep : absolute, SEQEND_fullstep : absolute
SEQ_goalertstand = 284
SEQEND_goalertstand = 286
        .export SEQ_goalertstand : absolute, SEQEND_goalertstand : absolute
SEQ_guardengarde = 311
SEQEND_guardengarde = 314
        .export SEQ_guardengarde : absolute, SEQEND_guardengarde : absolute
SEQ_guy3 = 442
SEQEND_guy3 = 443
        .export SEQ_guy3 : absolute, SEQEND_guy3 : absolute
SEQ_guy4 = 443
SEQEND_guy4 = 446
        .export SEQ_guy4 : absolute, SEQEND_guy4 : absolute
SEQ_guy5 = 446
SEQEND_guy5 = 447
        .export SEQ_guy5 : absolute, SEQEND_guy5 : absolute
SEQ_guy6 = 447
SEQEND_guy6 = 448
        .export SEQ_guy6 : absolute, SEQEND_guy6 : absolute
SEQ_guy7 = 448
SEQEND_guy7 = 451
        .export SEQ_guy7 : absolute, SEQEND_guy7 : absolute
SEQ_guy8 = 451
SEQEND_guy8 = 454
        .export SEQ_guy8 : absolute, SEQEND_guy8 : absolute
SEQ_guy9 = 454
SEQEND_guy9 = 458
        .export SEQ_guy9 : absolute, SEQEND_guy9 : absolute
SEQ_halve = 2116
SEQEND_halve = 2124
        .export SEQ_halve : absolute, SEQEND_halve : absolute
SEQ_hang = 1046
SEQEND_hang = 1049
        .export SEQ_hang : absolute, SEQEND_hang : absolute
SEQ_hang1 = 1049
SEQEND_hang1 = 1094
        .export SEQ_hang1 : absolute, SEQEND_hang1 : absolute
SEQ_hangdrop = 1178
SEQEND_hangdrop = 1197
        .export SEQ_hangdrop : absolute, SEQEND_hangdrop : absolute
SEQ_hangfall = 1197
SEQEND_hangfall = 1216
        .export SEQ_hangfall : absolute, SEQEND_hangfall : absolute
SEQ_hangstraight = 1094
SEQEND_hangstraight = 1107
        .export SEQ_hangstraight : absolute, SEQEND_hangstraight : absolute
SEQ_hardbump = 1460
SEQEND_hardbump = 1490
        .export SEQ_hardbump : absolute, SEQEND_hardbump : absolute
SEQ_hardland = 2071
SEQEND_hardland = 2084
        .export SEQ_hardland : absolute, SEQEND_hardland : absolute
SEQ_highjump = 1268
SEQEND_highjump = 1298
        .export SEQ_highjump : absolute, SEQEND_highjump : absolute
SEQ_impale = 2105
SEQEND_impale = 2116
        .export SEQ_impale : absolute, SEQEND_impale : absolute
SEQ_jumpbackhang = 1017
SEQEND_jumpbackhang = 1046
        .export SEQ_jumpbackhang : absolute, SEQEND_jumpbackhang : absolute
SEQ_jumpfall = 913
SEQEND_jumpfall = 941
        .export SEQ_jumpfall : absolute, SEQEND_jumpfall : absolute
SEQ_jumphangLong = 990
SEQEND_jumphangLong = 1017
        .export SEQ_jumphangLong : absolute, SEQEND_jumphangLong : absolute
SEQ_jumphangMed = 969
SEQEND_jumphangMed = 990
        .export SEQ_jumphangMed : absolute, SEQEND_jumphangMed : absolute
SEQ_jumpup = 1247
SEQEND_jumpup = 1268
        .export SEQ_jumpup : absolute, SEQEND_jumpup : absolute
SEQ_landengarde = 478
SEQEND_landengarde = 484
        .export SEQ_landengarde : absolute, SEQEND_landengarde : absolute
SEQ_landrun = 1973
SEQEND_landrun = 2005
        .export SEQ_landrun : absolute, SEQEND_landrun : absolute
SEQ_medland = 2005
SEQEND_medland = 2071
        .export SEQ_medland : absolute, SEQEND_medland : absolute
SEQ_patchfall = 879
SEQEND_patchfall = 886
        .export SEQ_patchfall : absolute, SEQEND_patchfall : absolute
SEQ_pickupsword = 1859
SEQEND_pickupsword = 1875
        .export SEQ_pickupsword : absolute, SEQEND_pickupsword : absolute
SEQ_rdiveroll = 634
SEQEND_rdiveroll = 656
        .export SEQ_rdiveroll : absolute, SEQEND_rdiveroll : absolute
SEQ_ready = 328
SEQEND_ready = 338
        .export SEQ_ready : absolute, SEQEND_ready : absolute
SEQ_readyblock = 468
SEQEND_readyblock = 469
        .export SEQ_readyblock : absolute, SEQEND_readyblock : absolute
SEQ_resheathe = 1875
SEQEND_resheathe = 1908
        .export SEQ_resheathe : absolute, SEQEND_resheathe : absolute
SEQ_retreat = 420
SEQEND_retreat = 434
        .export SEQ_retreat : absolute, SEQEND_retreat : absolute
SEQ_rjlandrun = 625
SEQEND_rjlandrun = 634
        .export SEQ_rjlandrun : absolute, SEQEND_rjlandrun : absolute
SEQ_rjumpfall = 941
SEQEND_rjumpfall = 969
        .export SEQ_rjumpfall : absolute, SEQEND_rjumpfall : absolute
SEQ_runcyc1 = 247
SEQEND_runcyc1 = 250
        .export SEQ_runcyc1 : absolute, SEQEND_runcyc1 : absolute
SEQ_runcyc2 = 250
SEQEND_runcyc2 = 253
        .export SEQ_runcyc2 : absolute, SEQEND_runcyc2 : absolute
SEQ_runcyc3 = 253
SEQEND_runcyc3 = 258
        .export SEQ_runcyc3 : absolute, SEQEND_runcyc3 : absolute
SEQ_runcyc4 = 258
SEQEND_runcyc4 = 261
        .export SEQ_runcyc4 : absolute, SEQEND_runcyc4 : absolute
SEQ_runcyc5 = 261
SEQEND_runcyc5 = 264
        .export SEQ_runcyc5 : absolute, SEQEND_runcyc5 : absolute
SEQ_runcyc6 = 264
SEQEND_runcyc6 = 267
        .export SEQ_runcyc6 : absolute, SEQEND_runcyc6 : absolute
SEQ_runcyc7 = 267
SEQEND_runcyc7 = 272
        .export SEQ_runcyc7 : absolute, SEQEND_runcyc7 : absolute
SEQ_runcyc8 = 272
SEQEND_runcyc8 = 278
        .export SEQ_runcyc8 : absolute, SEQEND_runcyc8 : absolute
SEQ_runjump = 579
SEQEND_runjump = 625
        .export SEQ_runjump : absolute, SEQEND_runjump : absolute
SEQ_running = 228
SEQEND_running = 233
        .export SEQ_running : absolute, SEQEND_running : absolute
SEQ_runstop = 1222
SEQEND_runstop = 1247
        .export SEQ_runstop : absolute, SEQEND_runstop : absolute
SEQ_runstt1 = 235
SEQEND_runstt1 = 236
        .export SEQ_runstt1 : absolute, SEQEND_runstt1 : absolute
SEQ_runstt2 = 236
SEQEND_runstt2 = 237
        .export SEQ_runstt2 : absolute, SEQEND_runstt2 : absolute
SEQ_runstt3 = 237
SEQEND_runstt3 = 238
        .export SEQ_runstt3 : absolute, SEQEND_runstt3 : absolute
SEQ_runstt4 = 238
SEQEND_runstt4 = 241
        .export SEQ_runstt4 : absolute, SEQEND_runstt4 : absolute
SEQ_runstt5 = 241
SEQEND_runstt5 = 244
        .export SEQ_runstt5 : absolute, SEQEND_runstt5 : absolute
SEQ_runstt6 = 244
SEQEND_runstt6 = 247
        .export SEQ_runstt6 : absolute, SEQEND_runstt6 : absolute
SEQ_runturn = 719
SEQEND_runturn = 762
        .export SEQ_runturn : absolute, SEQEND_runturn : absolute
SEQ_sdiveroll = 656
SEQEND_sdiveroll = 656
        .export SEQ_sdiveroll : absolute, SEQEND_sdiveroll : absolute
SEQ_sjland = 550
SEQEND_sjland = 579
        .export SEQ_sjland : absolute, SEQEND_sjland : absolute
SEQ_softland = 1954
SEQEND_softland = 1973
        .export SEQ_softland : absolute, SEQEND_softland : absolute
SEQ_stabbed = 338
SEQEND_stabbed = 367
        .export SEQ_stabbed : absolute, SEQEND_stabbed : absolute
SEQ_stabkill = 2084
SEQEND_stabkill = 2089
        .export SEQ_stabkill : absolute, SEQEND_stabkill : absolute
SEQ_stand = 278
SEQEND_stand = 284
        .export SEQ_stand : absolute, SEQEND_stand : absolute
SEQ_standjump = 521
SEQEND_standjump = 550
        .export SEQ_standjump : absolute, SEQEND_standjump : absolute
SEQ_standup = 1836
SEQEND_standup = 1859
        .export SEQ_standup : absolute, SEQEND_standup : absolute
SEQ_startrun = 233
SEQEND_startrun = 235
        .export SEQ_startrun : absolute, SEQEND_startrun : absolute
SEQ_step1 = 1815
SEQEND_step1 = 1824
        .export SEQ_step1 : absolute, SEQEND_step1 : absolute
SEQ_step10 = 1648
SEQEND_step10 = 1653
        .export SEQ_step10 : absolute, SEQEND_step10 : absolute
SEQ_step10a = 1653
SEQEND_step10a = 1676
        .export SEQ_step10a : absolute, SEQEND_step10a : absolute
SEQ_step11 = 1619
SEQEND_step11 = 1648
        .export SEQ_step11 : absolute, SEQEND_step11 : absolute
SEQ_step12 = 1588
SEQEND_step12 = 1619
        .export SEQ_step12 : absolute, SEQEND_step12 : absolute
SEQ_step13 = 1557
SEQEND_step13 = 1588
        .export SEQ_step13 : absolute, SEQEND_step13 : absolute
SEQ_step14 = 1526
SEQEND_step14 = 1526
        .export SEQ_step14 : absolute, SEQEND_step14 : absolute
SEQ_step2 = 1803
SEQEND_step2 = 1815
        .export SEQ_step2 : absolute, SEQEND_step2 : absolute
SEQ_step3 = 1787
SEQEND_step3 = 1803
        .export SEQ_step3 : absolute, SEQEND_step3 : absolute
SEQ_step4 = 1771
SEQEND_step4 = 1787
        .export SEQ_step4 : absolute, SEQEND_step4 : absolute
SEQ_step5 = 1750
SEQEND_step5 = 1771
        .export SEQ_step5 : absolute, SEQEND_step5 : absolute
SEQ_step6 = 1729
SEQEND_step6 = 1750
        .export SEQ_step6 : absolute, SEQEND_step6 : absolute
SEQ_step7 = 1708
SEQEND_step7 = 1729
        .export SEQ_step7 : absolute, SEQEND_step7 : absolute
SEQ_step8 = 1682
SEQEND_step8 = 1708
        .export SEQ_step8 : absolute, SEQEND_step8 : absolute
SEQ_step9 = 1676
SEQEND_step9 = 1682
        .export SEQ_step9 : absolute, SEQEND_step9 : absolute
SEQ_stepback = 1521
SEQEND_stepback = 1526
        .export SEQ_stepback : absolute, SEQEND_stepback : absolute
SEQ_stepfall = 848
SEQEND_stepfall = 857
        .export SEQ_stepfall : absolute, SEQEND_stepfall : absolute
SEQ_stepfall2 = 886
SEQEND_stepfall2 = 891
        .export SEQ_stepfall2 : absolute, SEQEND_stepfall2 : absolute
SEQ_stepfloat = 891
SEQEND_stepfloat = 913
        .export SEQ_stepfloat : absolute, SEQEND_stepfloat : absolute
SEQ_stoop = 1824
SEQEND_stoop = 1836
        .export SEQ_stoop : absolute, SEQEND_stoop : absolute
SEQ_strike = 434
SEQEND_strike = 440
        .export SEQ_strike : absolute, SEQEND_strike : absolute
SEQ_strikeadv = 367
SEQEND_strikeadv = 381
        .export SEQ_strikeadv : absolute, SEQEND_strikeadv : absolute
SEQ_strikeblock = 473
SEQEND_strikeblock = 478
        .export SEQ_strikeblock : absolute, SEQEND_strikeblock : absolute
SEQ_strikeret = 381
SEQEND_strikeret = 393
        .export SEQ_strikeret : absolute, SEQEND_strikeret : absolute
SEQ_superhijump = 1298
SEQEND_superhijump = 1389
        .export SEQ_superhijump : absolute, SEQEND_superhijump : absolute
SEQ_testfoot = 1490
SEQEND_testfoot = 1521
        .export SEQ_testfoot : absolute, SEQEND_testfoot : absolute
SEQ_turn = 686
SEQEND_turn = 700
        .export SEQ_turn : absolute, SEQEND_turn : absolute
SEQ_turndraw = 674
SEQEND_turndraw = 686
        .export SEQ_turndraw : absolute, SEQEND_turndraw : absolute
SEQ_turnengarde = 505
SEQEND_turnengarde = 513
        .export SEQ_turnengarde : absolute, SEQEND_turnengarde : absolute
SEQ_turnrun = 712
SEQEND_turnrun = 719
        .export SEQ_turnrun : absolute, SEQEND_turnrun : absolute

        .segment "SEQDATA"
SEQTABLE:
        .byte $e9,$30,$16,$31,$09,$32,$43,$32,$ae,$32,$cf,$32,$50,$33,$c9,$33
        .byte $16,$34,$79,$34,$9a,$34,$c0,$34,$c6,$34,$df,$34,$6d,$35,$f9,$33
        .byte $a2,$37,$91,$33,$76,$33,$d5,$37,$ad,$33,$17,$38,$ad,$34,$de,$33
        .byte $46,$34,$7a,$32,$90,$32,$f4,$34,$17,$37,$0b,$37,$fb,$36,$eb,$36
        .byte $d6,$36,$c1,$36,$ac,$36,$92,$36,$8c,$36,$70,$36,$53,$36,$34,$36
        .byte $15,$36,$f6,$35,$c8,$32,$d2,$35,$7f,$35,$b4,$35,$75,$35,$12,$35
        .byte $2c,$37,$20,$37,$39,$38,$4c,$38,$4f,$38,$44,$38,$3a,$31,$89,$31
        .byte $a4,$31,$b2,$31,$f2,$31,$f9,$31,$d9,$31,$d4,$31,$de,$31,$e4,$31
        .byte $eb,$31,$d0,$31,$6f,$31,$63,$34,$ca,$31,$58,$38,$29,$38,$f1,$35
        .byte $53,$34,$52,$31,$b8,$31,$7d,$31,$1e,$31,$82,$37,$90,$32,$01,$32
        .byte $fa,$32,$16,$33,$34,$33,$e4,$30,$24,$38,$98,$31,$1c,$31,$22,$31
        .byte $a2,$32,$37,$31,$43,$37,$53,$37,$74,$37,$14,$39,$b5,$38,$ce,$38
        .byte $e5,$38,$18,$39,$27,$39,$ec,$38,$ed,$39,$b9,$38,$3b,$39,$6f,$33
        .byte $c4,$39,$d2,$39,$da,$39,$43,$39,$3f,$39,$65,$39,$69,$39,$7b,$39
        .byte $bf,$39,$d6,$39,$f9,$01,$ff,$f7,$30,$f9,$01,$01,$02,$03,$04,$fb
        .byte $08,$05,$fb,$03,$06,$fb,$03,$07,$fb,$05,$08,$fb,$01,$f2,$01,$09
        .byte $fb,$02,$0a,$fb,$04,$0b,$fb,$05,$0c,$fb,$02,$f2,$01,$0d,$fb,$03
        .byte $0e,$fb,$04,$ff,$f7,$30,$f9,$00,$0f,$ff,$16,$31,$f9,$01,$a6,$ff
        .byte $1e,$31,$f9,$05,$fb,$0a,$b1,$b1,$fb,$f9,$fa,$fe,$b2,$fb,$05,$fa
        .byte $02,$a6,$fb,$ff,$ff,$48,$31,$ff,$48,$31,$f9,$01,$fb,$02,$cf,$d0
        .byte $fb,$02,$d1,$fb,$02,$d2,$fb,$03,$f9,$01,$f2,$00,$9e,$aa,$ab,$ff
        .byte $4e,$31,$f9,$05,$f8,$ff,$00,$ac,$fb,$ff,$fa,$01,$ad,$fb,$ff,$ae
        .byte $fb,$ff,$fa,$02,$fb,$fe,$fa,$01,$fb,$fb,$fa,$fc,$ff,$c3,$31,$f9
        .byte $01,$f8,$01,$00,$9b,$fb,$02,$a5,$fb,$fe,$ff,$48,$31,$f9,$01,$f8
        .byte $ff,$00,$9b,$9c,$9d,$9e,$ff,$a4,$31,$f9,$01,$f8,$01,$00,$fb,$02
        .byte $a3,$fb,$04,$a4,$a5,$ff,$48,$31,$f9,$01,$f8,$01,$00,$fb,$06,$a4
        .byte $a5,$ff,$48,$31,$f9,$01,$f8,$ff,$00,$fb,$fd,$a0,$fb,$fe,$9d,$ff
        .byte $48,$31,$f9,$01,$f8,$ff,$00,$a8,$f9,$01,$97,$f9,$01,$98,$99,$9a
        .byte $f9,$05,$9b,$f9,$01,$9c,$9d,$ff,$48,$31,$f9,$01,$a7,$ff,$c0,$31
        .byte $a2,$ff,$bb,$31,$a9,$96,$ff,$48,$31,$9f,$a0,$ff,$d5,$31,$f9,$01
        .byte $f4,$ff,$48,$31,$f9,$05,$fb,$f8,$ff,$48,$31,$f9,$05,$a0,$9d,$ff
        .byte $48,$31,$f9,$07,$fb,$f8,$ff,$ae,$32,$f9,$05,$fe,$fb,$05,$ff,$a4
        .byte $31,$f9,$05,$fe,$fb,$12,$ff,$1c,$31,$f9,$01,$10,$11,$fb,$02,$12
        .byte $fb,$02,$13,$fb,$02,$14,$fb,$02,$15,$fb,$02,$16,$fb,$07,$17,$fb
        .byte $09,$18,$fb,$05,$fa,$fa,$19,$fb,$01,$fa,$06,$1a,$fb,$04,$f4,$f2
        .byte $01,$1b,$fb,$fd,$1c,$fb,$05,$1d,$f2,$01,$1e,$1f,$20,$21,$fb,$01
        .byte $ff,$16,$31,$f9,$01,$f2,$01,$22,$fb,$05,$23,$fb,$06,$24,$fb,$03
        .byte $25,$fb,$05,$f2,$01,$26,$fb,$07,$27,$fb,$0c,$fa,$fd,$28,$fb,$08
        .byte $fa,$f7,$29,$fb,$08,$fa,$fe,$2a,$fb,$04,$fa,$0b,$2b,$fb,$04,$fa
        .byte $03,$2c,$fb,$05,$f4,$f2,$01,$ff,$f7,$30,$f9,$01,$fb,$01,$6b,$fb
        .byte $02,$fb,$02,$6c,$fb,$02,$6d,$fb,$02,$6d,$fb,$02,$6d,$ff,$8c,$32
        .byte $f9,$01,$fb,$01,$6e,$6f,$fb,$02,$70,$fb,$02,$6c,$fb,$02,$6d,$ff
        .byte $9e,$32,$f9,$07,$fe,$fb,$06,$2d,$fb,$01,$2e,$ff,$3a,$31,$f9,$07
        .byte $fe,$fb,$06,$2d,$fb,$01,$2e,$fb,$02,$2f,$fb,$ff,$30,$fb,$01,$31
        .byte $fb,$fe,$32,$33,$34,$ff,$16,$31,$f9,$01,$fb,$ff,$ff,$eb,$30,$f9
        .byte $01,$fb,$01,$35,$fb,$01,$f2,$01,$36,$fb,$08,$37,$f2,$01,$38,$fb
        .byte $07,$39,$fb,$03,$3a,$fb,$01,$3b,$3c,$fb,$02,$3d,$fb,$ff,$3e,$3f
        .byte $40,$fb,$ff,$41,$fb,$f2,$fe,$ff,$0b,$31,$f9,$03,$fa,$ff,$66,$fb
        .byte $fe,$fa,$06,$67,$fb,$fe,$fa,$09,$68,$fb,$ff,$fa,$0c,$69,$fb,$fd
        .byte $f8,$00,$0f,$ff,$c0,$34,$f9,$03,$fa,$ff,$fb,$fe,$66,$fb,$fd,$fa
        .byte $06,$67,$fb,$fd,$fa,$09,$68,$fb,$fe,$fa,$0c,$69,$fb,$fd,$f8,$00
        .byte $0f,$ff,$c0,$34,$f9,$03,$fb,$01,$fa,$ff,$66,$fb,$02,$fa,$06,$67
        .byte $fb,$ff,$fa,$09,$68,$fa,$0c,$69,$fb,$fe,$f8,$01,$0f,$ff,$c0,$34
        .byte $f9,$03,$fb,$01,$fa,$03,$f7,$7b,$33,$66,$fb,$02,$fa,$06,$67,$fb
        .byte $ff,$fa,$09,$68,$fa,$0c,$69,$fb,$fe,$f8,$01,$0f,$ff,$c0,$34,$fb
        .byte $ff,$fa,$fd,$ff,$59,$33,$fb,$01,$ff,$50,$33,$66,$fb,$02,$fa,$03
        .byte $67,$fb,$ff,$fa,$04,$68,$fa,$05,$69,$fb,$fe,$f8,$01,$06,$ff,$c0
        .byte $34,$f9,$03,$fb,$01,$fa,$03,$66,$fb,$02,$fa,$06,$67,$fb,$01,$fa
        .byte $09,$68,$fb,$02,$fa,$0c,$69,$f8,$02,$0f,$ff,$c0,$34,$f9,$03,$fb
        .byte $01,$fa,$03,$66,$fb,$03,$fa,$06,$67,$fb,$02,$fa,$09,$68,$fb,$03
        .byte $fa,$0c,$69,$f8,$03,$0f,$ff,$c0,$34,$f9,$01,$43,$44,$45,$46,$47
        .byte $48,$49,$4a,$4b,$4c,$4d,$f9,$02,$4e,$4f,$50,$ff,$16,$34,$f9,$01
        .byte $43,$44,$45,$46,$47,$48,$49,$4a,$4b,$4c,$4d,$f9,$02,$fb,$01,$4e
        .byte $fb,$02,$4f,$fb,$01,$50,$ff,$16,$34,$f9,$01,$43,$44,$45,$46,$47
        .byte $48,$49,$4a,$4b,$4c,$fb,$ff,$4d,$f9,$02,$fb,$fe,$4e,$fb,$ff,$4f
        .byte $fb,$ff,$50,$ff,$16,$34,$f9,$02,$5b,$5a,$59,$58,$57,$57,$57,$58
        .byte $59,$5a,$5b,$5c,$5d,$5e,$5f,$60,$61,$62,$63,$61,$60,$5f,$5e,$5d
        .byte $5c,$5b,$5a,$59,$58,$57,$58,$59,$5a,$5b,$5c,$5d,$5e,$5f,$60,$5f
        .byte $5e,$5d,$5c,$ff,$9a,$34,$f9,$06,$f2,$02,$5c,$5d,$5d,$5c,$5c,$5b
        .byte $ff,$4f,$34,$87,$88,$89,$89,$8a,$8a,$8a,$8a,$89,$88,$87,$fb,$f9
        .byte $ff,$9a,$34,$f9,$01,$94,$91,$90,$8f,$8e,$8d,$fb,$fb,$fa,$3f,$fc
        .byte $f9,$03,$8c,$8a,$88,$5b,$ff,$19,$34,$f9,$01,$87,$88,$89,$8a,$8b
        .byte $8c,$fb,$05,$fa,$c1,$fd,$8d,$8e,$8f,$90,$91,$92,$93,$94,$f9,$05
        .byte $95,$f9,$01,$76,$77,$fb,$01,$ff,$16,$31,$f9,$00,$51,$52,$f9,$05
        .byte $53,$f9,$01,$f4,$f2,$00,$54,$55,$fb,$03,$ff,$16,$31,$f9,$03,$51
        .byte $fa,$06,$51,$fa,$09,$51,$fa,$0c,$fb,$02,$f8,$00,$0c,$ff,$c0,$34
        .byte $f9,$04,$6a,$ff,$c2,$34,$f9,$01,$35,$fb,$02,$f2,$01,$36,$fb,$07
        .byte $37,$f2,$01,$38,$fb,$02,$31,$fb,$fe,$32,$33,$34,$ff,$16,$31,$f9
        .byte $01,$43,$44,$45,$46,$47,$48,$49,$4a,$4b,$4c,$4d,$4e,$f9,$00,$f5
        .byte $4f,$ff,$9a,$34,$f9,$01,$43,$44,$45,$46,$47,$48,$49,$4a,$4b,$4c
        .byte $4d,$4e,$4f,$fa,$fc,$4f,$fa,$fe,$4f,$4f,$fa,$02,$4f,$fa,$04,$ff
        .byte $9a,$34,$43,$44,$45,$46,$47,$48,$49,$4a,$4b,$4c,$fa,$ff,$4d,$fa
        .byte $fd,$4e,$fa,$fc,$4f,$fa,$f6,$4f,$fa,$f7,$4f,$fa,$f8,$4f,$fa,$f9
        .byte $4f,$fa,$fa,$4f,$fa,$fb,$4f,$fa,$fc,$4f,$fa,$fd,$4f,$fa,$fe,$4f
        .byte $fa,$fe,$4f,$fa,$ff,$4f,$fa,$ff,$4f,$fa,$ff,$4f,$4f,$4f,$4f,$fa
        .byte $01,$4f,$fa,$01,$4f,$fa,$02,$4f,$fa,$02,$4f,$fa,$03,$4f,$fa,$04
        .byte $4f,$fa,$05,$4f,$fa,$06,$4f,$f8,$00,$06,$ff,$c0,$34,$f9,$03,$50
        .byte $f2,$01,$ff,$16,$34,$f9,$05,$fb,$fc,$32,$33,$34,$ff,$16,$31,$f9
        .byte $05,$fb,$01,$fa,$03,$f7,$9e,$35,$66,$fb,$02,$fa,$06,$67,$fb,$ff
        .byte $fa,$09,$68,$fa,$0c,$69,$fb,$fe,$f8,$00,$0f,$ff,$c0,$34,$66,$fb
        .byte $02,$fa,$03,$67,$fb,$ff,$fa,$04,$68,$fa,$05,$69,$fb,$fe,$f8,$00
        .byte $06,$ff,$c0,$34,$f9,$05,$fb,$ff,$fa,$fc,$66,$fb,$ff,$fa,$03,$fb
        .byte $fd,$fa,$01,$f4,$fb,$01,$f2,$01,$6b,$fb,$02,$6c,$f2,$01,$6d,$ff
        .byte $2c,$37,$79,$fb,$01,$7a,$7b,$fb,$02,$7c,$fb,$04,$7d,$fb,$03,$7e
        .byte $fb,$fc,$56,$f2,$01,$f4,$fb,$fc,$74,$fb,$fe,$75,$76,$77,$ff,$16
        .byte $31,$fb,$fb,$ff,$16,$31,$f9,$01,$79,$fb,$01,$7a,$fb,$01,$7b,$fb
        .byte $03,$7c,$fb,$04,$7d,$fb,$03,$7e,$fb,$ff,$fb,$03,$7f,$80,$81,$82
        .byte $83,$84,$ff,$16,$31,$f9,$01,$79,$fb,$01,$7a,$fb,$01,$7b,$fb,$03
        .byte $7c,$fb,$04,$7d,$fb,$03,$7e,$fb,$ff,$fb,$02,$7f,$80,$81,$82,$83
        .byte $84,$ff,$16,$31,$f9,$01,$79,$fb,$01,$7a,$fb,$01,$7b,$fb,$03,$7c
        .byte $fb,$04,$7d,$fb,$03,$7e,$fb,$ff,$fb,$01,$7f,$80,$81,$82,$83,$84
        .byte $ff,$16,$31,$f9,$01,$79,$fb,$01,$7a,$fb,$01,$7b,$fb,$03,$7c,$fb
        .byte $04,$7d,$fb,$03,$7e,$fb,$ff,$7f,$80,$81,$82,$83,$84,$ff,$16,$31
        .byte $f9,$01,$79,$fb,$01,$7a,$fb,$01,$7b,$fb,$03,$7c,$fb,$04,$7d,$fb
        .byte $03,$7e,$fb,$fe,$80,$81,$82,$83,$84,$ff,$16,$31,$f9,$01,$79,$ff
        .byte $75,$36,$f9,$01,$79,$fb,$01,$7a,$fb,$01,$7b,$fb,$03,$7c,$fb,$04
        .byte $7d,$fb,$ff,$7f,$80,$81,$82,$83,$84,$ff,$16,$31,$f9,$01,$79,$fb
        .byte $01,$7a,$fb,$01,$7b,$fb,$03,$7c,$fb,$02,$81,$82,$83,$84,$ff,$16
        .byte $31,$f9,$01,$79,$fb,$01,$7a,$fb,$01,$7b,$fb,$02,$7c,$fb,$02,$81
        .byte $82,$83,$84,$ff,$16,$31,$f9,$01,$79,$fb,$01,$7a,$fb,$01,$7b,$fb
        .byte $02,$7c,$fb,$01,$81,$82,$83,$84,$ff,$16,$31,$f9,$01,$79,$fb,$01
        .byte $7a,$fb,$01,$7b,$fb,$02,$83,$84,$ff,$16,$31,$f9,$01,$79,$fb,$01
        .byte $7a,$fb,$01,$7b,$fb,$01,$83,$84,$ff,$16,$31,$f9,$01,$79,$fb,$01
        .byte $7a,$fb,$01,$84,$ff,$16,$31,$f9,$01,$79,$fb,$01,$84,$ff,$16,$31
        .byte $f9,$01,$fb,$01,$6b,$fb,$02,$6c,$6d,$ff,$28,$37,$f9,$05,$fb,$01
        .byte $6e,$6f,$fb,$02,$70,$71,$fb,$01,$72,$73,$74,$fb,$fc,$75,$76,$77
        .byte $ff,$16,$31,$f9,$01,$f3,$01,$e5,$e5,$e5,$e5,$e5,$e5,$e6,$e7,$e8
        .byte $ff,$53,$37,$f9,$01,$fb,$fb,$e9,$ea,$eb,$ec,$ed,$ee,$ef,$f0,$85
        .byte $85,$86,$86,$86,$30,$fb,$01,$31,$fb,$fe,$f9,$05,$32,$f9,$01,$33
        .byte $34,$ff,$16,$31,$f9,$01,$fb,$fb,$ea,$ec,$ee,$f0,$86,$fb,$ff,$ff
        .byte $16,$31,$f9,$01,$fb,$04,$bf,$c0,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8
        .byte $c9,$ca,$cb,$cc,$cd,$cd,$cd,$f3,$01,$cd,$cd,$c9,$c6,$fb,$fc,$ff
        .byte $16,$31,$f9,$05,$f4,$fb,$01,$f2,$01,$6b,$fb,$02,$6c,$f2,$01,$f9
        .byte $01,$6d,$ff,$b1,$37,$f9,$01,$fa,$fe,$fb,$01,$6b,$fb,$02,$6c,$6d
        .byte $fb,$01,$6e,$6f,$fb,$02,$70,$71,$fb,$01,$fa,$01,$72,$fa,$01,$73
        .byte $fb,$fe,$ff,$ee,$30,$f9,$05,$f4,$fa,$fe,$fb,$01,$fb,$02,$6c,$6d
        .byte $6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d
        .byte $6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$6d,$fb,$01,$6e,$6e
        .byte $6e,$6f,$fb,$02,$70,$71,$fb,$01,$fa,$01,$72,$fa,$01,$73,$74,$fb
        .byte $fc,$75,$76,$77,$ff,$16,$31,$f9,$05,$f4,$fa,$fe,$fb,$03,$b9,$f6
        .byte $b9,$ff,$20,$38,$f9,$05,$ff,$29,$38,$f9,$01,$f6,$b3,$b4,$b5,$b6
        .byte $fb,$01,$b7,$fb,$fc,$b9,$ff,$35,$38,$f9,$01,$f4,$fb,$04,$b1,$f6
        .byte $b1,$ff,$40,$38,$f9,$01,$b2,$f6,$b2,$ff,$48,$38,$ff,$d5,$37,$f8
        .byte $00,$00,$f9,$04,$b9,$ff,$54,$38,$f9,$05,$fb,$fb,$fa,$ff,$f2,$01
        .byte $d9,$da,$db,$fb,$01,$dc,$fb,$fc,$fa,$fd,$f2,$01,$dd,$fb,$fc,$fa
        .byte $fe,$de,$de,$fb,$fe,$fa,$fd,$df,$df,$fb,$fd,$fa,$f8,$f2,$01,$e0
        .byte $e0,$fb,$ff,$fa,$ff,$e1,$e1,$fb,$fd,$fa,$fc,$e2,$e2,$fb,$ff,$fa
        .byte $fb,$f2,$01,$e3,$e3,$fb,$fe,$fa,$ff,$e4,$e4,$00,$f2,$01,$00,$00
        .byte $00,$00,$f2,$01,$00,$00,$00,$00,$f2,$01,$00,$00,$00,$00,$f2,$01
        .byte $f1,$00,$ff,$b1,$38,$36,$ff,$b5,$38,$55,$43,$43,$43,$43,$43,$43
        .byte $44,$45,$46,$47,$48,$49,$4a,$4b,$53,$54,$4c,$ff,$ca,$38,$fb,$01
        .byte $30,$fb,$02,$31,$fb,$06,$32,$fb,$01,$33,$fb,$ff,$34,$fb,$01,$35
        .byte $fb,$01,$ff,$d0,$38,$fb,$01,$37,$38,$ff,$b5,$38,$4d,$4e,$4f,$50
        .byte $51,$52,$fb,$01,$36,$36,$36,$36,$36,$36,$39,$3a,$3b,$3c,$3d,$fb
        .byte $02,$3e,$fb,$ff,$3f,$fb,$fd,$40,$41,$fb,$ff,$42,$fe,$fb,$10,$fb
        .byte $03,$ff,$d3,$38,$0b,$ff,$14,$39,$02,$03,$04,$05,$06,$07,$08,$09
        .byte $fe,$fb,$09,$0b,$ff,$14,$39,$fe,$fb,$0b,$0c,$fb,$01,$0d,$fb,$01
        .byte $0e,$fb,$03,$0f,$fb,$01,$10,$11,$ff,$37,$39,$13,$ff,$3b,$39,$14
        .byte $ff,$3f,$39,$15,$fb,$01,$16,$17,$18,$fb,$01,$19,$fb,$fd,$1a,$fb
        .byte $fe,$1b,$fb,$fc,$1c,$fb,$fd,$1d,$fb,$fe,$1e,$fb,$fd,$1f,$fb,$ff
        .byte $20,$21,$ff,$61,$39,$25,$ff,$65,$39,$25,$26,$27,$28,$29,$2a,$2b
        .byte $2c,$2d,$2e,$2f,$fe,$fb,$0d,$0b,$ff,$77,$39,$0b,$0b,$fe,$fb,$0d
        .byte $2f,$2e,$2d,$2c,$2b,$2a,$29,$28,$27,$26,$25,$24,$24,$24,$23,$23
        .byte $23,$22,$22,$22,$22,$22,$22,$22,$23,$23,$24,$24,$24,$23,$23,$23
        .byte $22,$22,$22,$22,$22,$22,$22,$23,$23,$24,$24,$24,$23,$23,$23,$22
        .byte $22,$22,$22,$22,$22,$22,$22,$22,$23,$23,$23,$24,$ff,$bb,$39,$01
        .byte $12,$ff,$c0,$39,$f9,$01,$ba,$fb,$05,$ba,$fb,$03,$bb,$fb,$04,$ff
        .byte $c6,$39,$ba,$ff,$d2,$39,$bc,$ff,$d6,$39,$f9,$00,$ba,$ba,$ba,$bc
        .byte $bc,$bc,$bc,$bc,$bc,$bc,$bc,$fe,$fb,$08,$ff,$c6,$39,$ba,$ff,$ed
        .byte $39,$00
; 2546 bytes
